### PR TITLE
README.md: convert to markdown

### PR DESCRIPTION
**Pull request by Mikaela**

### CODE REVIEW

**Comment by Mikaela** [comment]
How it looks like: https://github.com/Mkaysi/http-redirector/blob/README.md/README.md#real-life-testing

In case there are formatting issues, please tell me. I wasn't sure about all parts.

Also https://github.com/rgeissert/http-redirector still points to http.debian.org directly under the repo name:

> Debian mirrors HTTP redirector http://http.debian.net/

**Comment by rgeissert** [comment]
Nice, thanks!

I spotted a couple of script names that could use some quoting, but that can be improved later on.

**Comment by rgeissert** [comment]
Oh, I actually need to modify the live index pages because they point to the README file. I won't be merging this change right now.

**Comment by rgeissert** [comment]
Merged and links updated, thanks again and apologies for taking so long

**Pull request closed without merging**
